name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  fl_chart: ^1.0.0
  http: ^1.4.0
  pdf: ^3.11.3
  path_provider: ^2.0.15
  open_file: ^3.5.10
  csv: ^5.0.0
  google_sign_in_web: 0.12.4+4
  file_saver: 0.2.14
  universal_html: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5


flutter:
  uses-material-design: true
  assets: 
    - assets/google_logo.png
