// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACeL-mRCcnDmibzHBZofZ1IhqpO8_bXik',
    appId: '1:258703844149:web:639f9a926a2ba4e792627c',
    messagingSenderId: '258703844149',
    projectId: 'expense-tracker-91ada',
    authDomain: 'expense-tracker-91ada.firebaseapp.com',
    storageBucket: 'expense-tracker-91ada.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAokkFp3D5iE94hyCGCrABPZn3TH8fwWqM',
    appId: '1:258703844149:android:a6bdce915d40b76992627c',
    messagingSenderId: '258703844149',
    projectId: 'expense-tracker-91ada',
    storageBucket: 'expense-tracker-91ada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_8EvQcsc1BVXxS5rTQ_53n2ayt7B53dc',
    appId: '1:258703844149:ios:e7cd3f9a61e67e4b92627c',
    messagingSenderId: '258703844149',
    projectId: 'expense-tracker-91ada',
    storageBucket: 'expense-tracker-91ada.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_8EvQcsc1BVXxS5rTQ_53n2ayt7B53dc',
    appId: '1:258703844149:ios:e7cd3f9a61e67e4b92627c',
    messagingSenderId: '258703844149',
    projectId: 'expense-tracker-91ada',
    storageBucket: 'expense-tracker-91ada.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACeL-mRCcnDmibzHBZofZ1IhqpO8_bXik',
    appId: '1:258703844149:web:68075e6fcfc5717e92627c',
    messagingSenderId: '258703844149',
    projectId: 'expense-tracker-91ada',
    authDomain: 'expense-tracker-91ada.firebaseapp.com',
    storageBucket: 'expense-tracker-91ada.firebasestorage.app',
  );
}
